package pretty

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/printer"
	"go/token"
	"io"
	"strings"

	"go.ufukty.com/gohandlers/internal/pretty/post"
	"go.ufukty.com/gohandlers/internal/version"
)

func stampVersion(w io.Writer) error {
	v, err := version.OfBuild()
	if err != nil {
		return fmt.Errorf("dig: %w", err)
	}
	_, err = fmt.Fprintf(w, "// Code generated by gohandlers %s. DO NOT EDIT.\n\n", v)
	if err != nil {
		return fmt.Errorf("writing: %w", err)
	}
	return nil
}

func Print(f *ast.File) (io.Reader, error) {
	b := bytes.NewBuffer([]byte{})
	err := stampVersion(b)
	if err != nil {
		return nil, fmt.Errorf("version stamping: %w", err)
	}
	err = printer.Fprint(b, token.NewFileSet(), f)
	if err != nil {
		return nil, fmt.Errorf("printing: %w", err)
	}
	proccessed, err := post.Process(b.String())
	if err != nil {
		return nil, fmt.Errorf("second print: %w", err)
	}
	formatted, err := format.Source([]byte(proccessed))
	if err != nil {
		return nil, fmt.Errorf("formatting: %w", err)
	}
	return strings.NewReader(string(formatted)), nil
}
