package implements

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/printer"
	"go/token"
	"gohandlers/pkg/inspects"
	"io"
	"os"
	"strings"

	"golang.org/x/exp/slices"
)

func recvn(s string) string {
	return strings.ToLower(string(s[0:2]))
}

func addnewlines(f string) string {
	f = strings.ReplaceAll(f, "HandlerInfo{", "HandlerInfo{\n") // beginning composite literal
	f = strings.ReplaceAll(f, "}, \"", "},\n\"")                // after each line
	f = strings.ReplaceAll(f, "}}", "},\n}")                    // ending composite literal
	return f
}

func HandlersFile(dst string, infoss map[string]map[string]inspects.Info, pkgname string, version string) error {
	f := &ast.File{
		Name: ast.NewIdent(pkgname),
		Decls: []ast.Decl{
			&ast.GenDecl{
				Tok:   token.IMPORT,
				Specs: []ast.Spec{&ast.ImportSpec{Path: &ast.BasicLit{Kind: token.STRING, Value: fmt.Sprintf("%q", "net/http")}}},
			},
			&ast.GenDecl{
				Tok: token.TYPE,
				Specs: []ast.Spec{&ast.TypeSpec{
					Name: &ast.Ident{Name: "HandlerInfo"},
					Type: &ast.StructType{Fields: &ast.FieldList{List: []*ast.Field{
						{
							Names: []*ast.Ident{{Name: "Method"}}, Type: &ast.Ident{Name: "string"},
						},
						{
							Names: []*ast.Ident{{Name: "Path"}}, Type: &ast.Ident{Name: "string"},
						},
						{
							Names: []*ast.Ident{{Name: "Ref"}},
							Type:  &ast.SelectorExpr{X: &ast.Ident{Name: "http"}, Sel: &ast.Ident{Name: "HandlerFunc"}},
						},
					}}},
				}},
			},
		},
	}

	fds := []ast.Decl{}
	for recvt, infos := range infoss {
		elts := []ast.Expr{}
		for hn, info := range infos {
			kv := &ast.KeyValueExpr{
				Key: &ast.BasicLit{Kind: token.STRING, Value: fmt.Sprintf("%q", hn)},
				Value: &ast.CompositeLit{Elts: []ast.Expr{
					&ast.KeyValueExpr{Key: &ast.Ident{Name: "Method"}, Value: &ast.BasicLit{Kind: token.STRING, Value: fmt.Sprintf("%q", info.Method)}},
					&ast.KeyValueExpr{Key: &ast.Ident{Name: "Path"}, Value: &ast.BasicLit{Kind: token.STRING, Value: fmt.Sprintf("%q", info.Path)}},
					&ast.KeyValueExpr{Key: &ast.Ident{Name: "Ref"}, Value: info.Ref},
				}},
			}
			elts = append(elts, kv)
		}

		slices.SortFunc(elts, func(a, b ast.Expr) int {
			ka := a.(*ast.KeyValueExpr).Key.(*ast.BasicLit).Value
			kb := b.(*ast.KeyValueExpr).Key.(*ast.BasicLit).Value
			if ka < kb {
				return -1
			} else if ka == kb {
				return 0
			} else {
				return 1
			}
		})

		fd := &ast.FuncDecl{
			Name: &ast.Ident{Name: "ListHandlers"},
			Type: &ast.FuncType{
				Params: &ast.FieldList{List: []*ast.Field{}},
				Results: &ast.FieldList{List: []*ast.Field{
					{Type: &ast.MapType{Key: &ast.Ident{Name: "string"}, Value: &ast.Ident{Name: "HandlerInfo"}}},
				}},
			},
			Body: &ast.BlockStmt{List: []ast.Stmt{
				&ast.ReturnStmt{Results: []ast.Expr{&ast.CompositeLit{
					Type: &ast.MapType{Key: &ast.Ident{Name: "string"}, Value: &ast.Ident{Name: "HandlerInfo"}},
					Elts: elts,
				}}},
			}},
		}

		if recvt != "" {
			fd.Recv = &ast.FieldList{List: []*ast.Field{{
				Names: []*ast.Ident{{Name: recvn(recvt)}},
				Type:  &ast.StarExpr{X: &ast.Ident{Name: recvt}},
			}}}
		}

		fds = append(fds, fd)
	}

	slices.SortFunc(fds, func(a, b ast.Decl) int {
		if a.(*ast.FuncDecl).Recv == nil {
			return -1
		}
		if b.(*ast.FuncDecl).Recv == nil {
			return 1
		}

		at := a.(*ast.FuncDecl).Recv.List[0].Type.(*ast.StarExpr).X.(*ast.Ident).Name
		bt := b.(*ast.FuncDecl).Recv.List[0].Type.(*ast.StarExpr).X.(*ast.Ident).Name

		if at < bt {
			return -1
		} else if at == bt {
			return 0
		} else {
			return 1
		}
	})
	f.Decls = append(f.Decls, fds...)

	b := bytes.NewBufferString("")
	fmt.Fprintf(b, "// Code generated by gohandlers %s. DO NOT EDIT.\n\n", version)
	err := printer.Fprint(b, token.NewFileSet(), f)
	if err != nil {
		return fmt.Errorf("printing: %w", err)
	}
	o, err := os.Create(dst)
	if err != nil {
		return fmt.Errorf("creating output file: %w", err)
	}
	defer o.Close()
	bt, err := format.Source([]byte(addnewlines(b.String())))
	if err != nil {
		return fmt.Errorf("formatting output file: %w", err)
	}
	io.Copy(o, bytes.NewBuffer(bt))

	return nil
}
